
package com.copel.sm.solman;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Inb_Sync_SM_CriarChamados_Leg_Req", targetNamespace = "urn:copel-com:sm:criarchamados_4800-sm_sync_soap-rfc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InbSyncSMCriarChamadosLegReq {


    /**
     * 
     * @param mtSMCriarChamadosLegReq
     * @return
     *     returns com.copel.sm.criarchamados_4800_sm_sync_soap_rfc.DTSMCriarChamadosLegResp
     */
    @WebMethod(operationName = "Inb_Sync_SM_CriarChamados_Leg_Req", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_SM_CriarChamados_Leg_Resp", targetNamespace = "urn:copel-com:sm:criarchamados_4800-sm_sync_soap-rfc", partName = "MT_SM_CriarChamados_Leg_Resp")
    public DTSMCriarChamadosLegResp inbSyncSMCriarChamadosLegReq(
        @WebParam(name = "MT_SM_CriarChamados_Leg_Req", targetNamespace = "urn:copel-com:sm:criarchamados_4800-sm_sync_soap-rfc", partName = "MT_SM_CriarChamados_Leg_Req")
        DTSMCriarChamadosLegReq mtSMCriarChamadosLegReq);

}
