
package com.copel.sm.solman;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Inb_Sync_SM_CriarChamados_Leg_ReqService", targetNamespace = "urn:copel-com:sm:criarchamados_4800-sm_sync_soap-rfc", wsdlLocation = "file:/C:/Temp/SOLMAN/solman.wsdl")
public class InbSyncSMCriarChamadosLegReqService
    extends Service
{

    private final static URL INBSYNCSMCRIARCHAMADOSLEGREQSERVICE_WSDL_LOCATION;
    private final static WebServiceException INBSYNCSMCRIARCHAMADOSLEGREQSERVICE_EXCEPTION;
    private final static QName INBSYNCSMCRIARCHAMADOSLEGREQSERVICE_QNAME = new QName("urn:copel-com:sm:criarchamados_4800-sm_sync_soap-rfc", "Inb_Sync_SM_CriarChamados_Leg_ReqService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Temp/SOLMAN/solman.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INBSYNCSMCRIARCHAMADOSLEGREQSERVICE_WSDL_LOCATION = url;
        INBSYNCSMCRIARCHAMADOSLEGREQSERVICE_EXCEPTION = e;
    }

    public InbSyncSMCriarChamadosLegReqService() {
        super(__getWsdlLocation(), INBSYNCSMCRIARCHAMADOSLEGREQSERVICE_QNAME);
    }

    public InbSyncSMCriarChamadosLegReqService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INBSYNCSMCRIARCHAMADOSLEGREQSERVICE_QNAME, features);
    }

    public InbSyncSMCriarChamadosLegReqService(URL wsdlLocation) {
        super(wsdlLocation, INBSYNCSMCRIARCHAMADOSLEGREQSERVICE_QNAME);
    }

    public InbSyncSMCriarChamadosLegReqService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INBSYNCSMCRIARCHAMADOSLEGREQSERVICE_QNAME, features);
    }

    public InbSyncSMCriarChamadosLegReqService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InbSyncSMCriarChamadosLegReqService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InbSyncSMCriarChamadosLegReq
     */
    @WebEndpoint(name = "Inb_Sync_SM_CriarChamados_Leg_ReqPort")
    public InbSyncSMCriarChamadosLegReq getInbSyncSMCriarChamadosLegReqPort() {
        return super.getPort(new QName("urn:copel-com:sm:criarchamados_4800-sm_sync_soap-rfc", "Inb_Sync_SM_CriarChamados_Leg_ReqPort"), InbSyncSMCriarChamadosLegReq.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InbSyncSMCriarChamadosLegReq
     */
    @WebEndpoint(name = "Inb_Sync_SM_CriarChamados_Leg_ReqPort")
    public InbSyncSMCriarChamadosLegReq getInbSyncSMCriarChamadosLegReqPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:copel-com:sm:criarchamados_4800-sm_sync_soap-rfc", "Inb_Sync_SM_CriarChamados_Leg_ReqPort"), InbSyncSMCriarChamadosLegReq.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INBSYNCSMCRIARCHAMADOSLEGREQSERVICE_EXCEPTION!= null) {
            throw INBSYNCSMCRIARCHAMADOSLEGREQSERVICE_EXCEPTION;
        }
        return INBSYNCSMCRIARCHAMADOSLEGREQSERVICE_WSDL_LOCATION;
    }

}
